Controllers/SurveysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TestCoreApp.Models;
using TestCoreApp.Models.Entities;
using Microsoft.AspNetCore.Authorization;
using TestCoreApp.Models.ViewModels.Surveys;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Identity;

namespace TestCoreApp.Controllers
{
    public class SurveysController : Controller
    {
        private readonly AppDbContext _db;
        private readonly UserManager<ApplicationUser> userManager;

        public SurveysController(AppDbContext context, UserManager<ApplicationUser> userManager)
        {
            this._db = context;
            this.userManager = userManager;
        }

        // GET: Surveys
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<Survey> mySurveys = await _db.Surveys.Include("Questions").ToListAsync();
            List<SurveyViewModel> svms = new List<SurveyViewModel>();
            foreach (Survey s in mySurveys)
            {
                var vm = new SurveyViewModel
                {
                    Name = s.Name,
                    Id = s.Id
                };
                var user = await userManager.GetUserAsync(HttpContext.User);
                if (user != null)
                {
                    var answerCount = _db.UserSurveyAnswers.Where(a => a.Answer.Question.BaseSurvey.Id == s.Id && a.User.Id == user.Id).Count();
                    if (answerCount == null)
                        vm.UserStatus = "NotStarted";
                    else if (answerCount == 0)
                        vm.UserStatus = "NotStarted";
                    else if (answerCount < s.Questions.Count)
                        vm.UserStatus = "Started";
                    else if (answerCount >= s.Questions.Count)
                        vm.UserStatus = "Finished";
                }
                svms.Add(vm);
            }

            return View(svms);
        }

        // GET: Surveys/Details/5
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            
            var survey = await _db.Surveys
                .FirstOrDefaultAsync(m => m.Id == id);
            if (survey == null)
            {
                return NotFound();
            }

            SurveyViewModel vm = new SurveyViewModel();
            vm.Id = survey.Id;
            vm.Name = survey.Name;
            vm.Description = survey.Description;
            vm.useQuestionDescriptions = survey.useQuestionDescriptions;
            vm.useAnswerDescriptions = survey.useAnswerDescriptions;
            vm.Questions = new List<SurveyQuestionViewModel>();

            var surveyQuestions = _db.SurveyQuestions.Where(c => c.BaseSurvey.Id == survey.Id).OrderBy(c => c.Sort).ToList();
            foreach (var q in surveyQuestions)
            {
                SurveyQuestionViewModel qvm = new SurveyQuestionViewModel();
                qvm.Id = q.Id;
                qvm.Sort = q.Sort;
                qvm.Name = q.Name;
                qvm.Description = q.Description;
                qvm.Answers = new List<SurveyAnswerViewModel>();
                var surveyAnswers = _db.SurveyAnswers.Where(a => a.Question.Id == q.Id).OrderBy(c => c.Sort).ToList();
                foreach (var a in surveyAnswers)
                {
                    System.Diagnostics.Debug.WriteLine("Found a survey answer: " + a.Name);
                    SurveyAnswerViewModel avm = new SurveyAnswerViewModel();
                    avm.Id = a.Id;
                    avm.Sort = a.Sort;
                    avm.Name = a.Name;
                    avm.Description = a.Description;
                    qvm.Answers.Add(avm);
                }
                vm.Questions.Add(qvm);
            }

            return View(vm);
        }

        // GET: Surveys/Create
        [Authorize(Roles = "Admin,Creator")]
        public IActionResult Create()
        {
            return View();
        }
        
        // POST: Surveys/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Creator")]
        public async Task<IActionResult> Create([Bind("Id,Name")] Survey survey)
        {
            if (ModelState.IsValid)
            {
                _db.Add(survey);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(survey);
        }

        // GET: Surveys/Edit/5
        [Authorize(Roles = "Admin,Creator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var survey = await _db.Surveys.FindAsync(id);
            if (survey == null)
            {
                return NotFound();
            }


            SurveyViewModel vm = new SurveyViewModel();
            vm.Id = survey.Id;
            vm.Name = survey.Name;
            vm.Description = survey.Description;
            vm.useQuestionDescriptions = survey.useQuestionDescriptions;
            vm.useAnswerDescriptions = survey.useAnswerDescriptions;
            vm.Questions = new List<SurveyQuestionViewModel>();


            var surveyQuestions = _db.SurveyQuestions.Where(c => c.BaseSurvey.Id == survey.Id).OrderBy(c => c.Sort).ToList();
            foreach (var q in surveyQuestions)
            {
                SurveyQuestionViewModel qvm = new SurveyQuestionViewModel();
                qvm.Id = q.Id;
                qvm.Sort = q.Sort;
                qvm.Name = q.Name;
                qvm.Description = q.Description;
                qvm.Answers = new List<SurveyAnswerViewModel>();
                var surveyAnswers = _db.SurveyAnswers.Where(a => a.Question.Id == q.Id).OrderBy(c => c.Sort).ToList();
                foreach (var a in surveyAnswers)
                {
                    System.Diagnostics.Debug.WriteLine("Found a survey answer: " + a.Name);
                    SurveyAnswerViewModel avm = new SurveyAnswerViewModel();
                    avm.Id = a.Id;
                    avm.Sort = a.Sort;
                    avm.Name = a.Name;
                    avm.Description = a.Description;
                    qvm.Answers.Add(avm);
                }
                vm.Questions.Add(qvm);
            }

            return View(vm);
        }

        // POST: Surveys/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Creator")]
        public async Task<IActionResult> Edit(int id,  Survey survey)
        {
            if (id != survey.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(survey);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SurveyExists(survey.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(survey);
        }

        // GET: Surveys/Delete/5
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var survey = await _db.Surveys
                .FirstOrDefaultAsync(m => m.Id == id);
            if (survey == null)
            {
                return NotFound();
            }

            return View(survey);
        }

        // POST: Surveys/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var survey = await _db.Surveys.FindAsync(id);
            _db.Surveys.Remove(survey);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SurveyExists(int id)
        {
            return _db.Surveys.Any(e => e.Id == id);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Creator")]
        public IActionResult saveSurvey(SurveyViewModel survey)
        {
            
            System.Diagnostics.Debug.WriteLine("Calling Save Survey! survey questions: " + survey.Questions.Count);
                        
            return Json(new
            {
                success = true,
                responseUrl = "/Home/Index/"
            });
        }



        [HttpPost]
        [Authorize(Roles = "Admin,Creator")]
        public  IActionResult addQuestion(int survey_id, int? question_id)
        {
            var survey = _db.Surveys
                .Include(s => s.Questions)
                .Where(s => s.Id == survey_id).FirstOrDefault();

            SurveyQuestion q = new SurveyQuestion
            {
                BaseSurvey = survey,
                Name = ".",
                Description = "."
            };
            survey.Questions.Add(q);
            _db.SaveChanges();

            return Json(new
            {
                success = true,

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using TestCoreApp.Models.Entities;
@inject SignInManager<ApplicationUser> signInManager;
@inject UserManager<ApplicationUser> userManager;

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pirate Party</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" />

    <link rel="stylesheet" href="~/css/uikit/uikit.min.css" />
    <link rel="stylesheet" href="~/css/uikit/uikit.gradient.min.css" />

    <link rel="stylesheet" href="~/css/uikit/components/tooltip.min.css" />
    <link rel="stylesheet" href="~/css/uikit/components/tooltip.gradient.min.css" />

    <link rel="stylesheet" href="~/lib/chart.js/Content/Chart.min.css" />

    <meta name="description" content="Lane County Pirate Party" />
    <link rel="shortcut icon" href="http://www.pirategov.org/images/parrot-icon.png">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img src="http://www.pirategov.org/images/PirateHead.png" style="height: 60px; " />
                <a class="navbar-brand survey-answer-name" asp-area="" asp-controller="Home" asp-action="Main">PirateGov</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex " style="vertical-align:middle">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link text-dark survey-answer-description" asp-controller="Home" asp-action="Declaration">Declaration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark survey-answer-description" asp-controller="Surveys" asp-action="Index">Surveys</a>
                        </li>
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark survey-answer-description" asp-controller="Admin" asp-action="ListRoles">Roles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark survey-answer-description" asp-controller="Admin" asp-action="ListUsers">Users</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form method="post" asp-action="Logout" asp-controller="Account">
                                    <button type="submit" class="nav-link btn btn-link py-0 survey-answer-name" style="width:auto">Logout @User.Identity.Name</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>

                        }
                    </ul>
                    @if (signInManager.IsSignedIn(User))
                    {
                        <img src="http://www.pirategov.org/images/treasure-chest.png" style="height: 60px; " />
                        var user = await @userManager.GetUserAsync(User);
                        <div class="pirate-gold">@user.PirateGold</div>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/font-awesome/js/all.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/uikit/uikit.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>